id: I84DAA1CD
legacy_id: P004252
ocr_import_info:
  bdrc_scan_id: W4CZ73
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T03:50:48'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T20:56:34.318527+00:00'
last_modified: 2022-09-04 04:56:51.742617
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ73
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ73
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསེར་འོད་དམ་པ་མདོ་སྡེའི་དབང་པོའི་རྒྱལ་པོ། ༼སོག་ཡིག༽
  author: སྣ་ནམ་བཙུན་པ་ཡེ་ཤེས་སྡེ།
statistics:
  ocr_word_mean_confidence_index: 0.5946641396701247
  ocr_word_median_confidence_index: 0.5899999737739563
quality: null
bases:
  I1KG13497:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13497
      total_pages: 554
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13497.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5946641396701247
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
