id: P004252
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W4CZ73
  title: གསེར་འོད་དམ་པ་མདོ་སྡེའི་དབང་པོའི་རྒྱལ་པོ། ༼སོག་ཡིག༽
  author: ''
  volumes:
    7d0d276200354bd885f76ee133a2105e:
      image_group_id: I1KG13497
      title: ''
      volume_number: 1
      total_pages: 554
      base_file: v001.txt
